CREATE TABLE transports
(
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id      BIGINT         NOT NULL,
    client_id       BIGINT         NOT NULL,
    vehicle_id      BIGINT         NOT NULL,
    driver_id       BIGINT         NOT NULL,
    cargo_type      VARCHAR(20)    NOT NULL COMMENT 'GOODS, PASSENGERS',
    cargo_name      VARCHAR(255),
    cargo_weight_kg DECIMAL(10, 2),
    passenger_count INT,
    start_location  VARCHAR(255)   NOT NULL,
    end_location    VARCHAR(255)   NOT NULL,
    departure_date  DATETIME       NOT NULL,
    arrival_date    DATETIME,
    price           DECIMAL(10, 2) NOT NULL,
    is_paid         BOOLEAN        NOT NULL DEFAULT FALSE,
    payment_date    DATETIME,
    created_at      DATETIME       NOT NULL,
    updated_at      DATETIME       NOT NULL,
    CONSTRAINT fk_transport_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transport_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transport_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transport_driver FOREIGN KEY (driver_id) REFERENCES employees (id) ON DELETE RESTRICT,
    INDEX          idx_transport_company_id (company_id),
    INDEX          idx_transport_client_id (client_id),
    INDEX          idx_transport_vehicle_id (vehicle_id),
    INDEX          idx_transport_driver_id (driver_id),
    INDEX          idx_transport_departure_date (departure_date),
    INDEX          idx_transport_is_paid (is_paid),
    INDEX          idx_transport_cargo_type (cargo_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;